### ISSUE TITLE
[Win11] does this work at all?

### ISSUE THREAD

**Issue by iceMongus** [Gkiokan/ps4-remote-pkg-sender#4] opened 2022-01-03 08:44 UTC
![Screenshot 2022-01-03 104130](https://user-images.githubusercontent.com/11286566/147912432-bb91b721-833f-4df1-8587-87d119c77772.jpg)

**Comment by Gkiokan** [comment] 2022-01-03 10:21
This looks similar to a race condition bug on windows 10 which was fixed before release.

Which Operating System are you running on? 

Thinks you can try:
- Quit the Application through the Menu `Application > Quit` (Kills all processes)
- Restart the Application (just to make sure this is not a random error)
- If still not working try open the App as Admin (allows to write the storage sync without running into the permission error caused by the race condition)

I cann't think of any other possible error yet. It may be a permission error. Would be very helpfull if you can provide more information about your OS.

**Comment by pgroot91** [comment] 2022-01-03 13:16
I have exactly the same as TS on Windows 11.

**Comment by Gkiokan** [comment] 2022-01-03 15:59
I will get win11 and start debugging. I'd already added bunch of fixes for win10 only before release. 
Let's tackle this, too.

I will keep you updated guys.

**Comment by iceMongus** [comment] 2022-01-03 17:18
it somehow runs !!.. sometimes runs and some do not. when run doing nothing !! when i try to upload the package and hit RESUME i got this msg
![Screenshot 2022-01-03 191413](https://user-images.githubusercontent.com/11286566/147959834-2c21a8df-cff8-4afc-867c-d4c8759784b7.jpg)

**Comment by iceMongus** [comment] 2022-01-03 17:26
![Screenshot 2022-01-03 192409](https://user-images.githubusercontent.com/11286566/147960578-93b12e39-29e3-408e-8e8f-b2130d3d3efc.jpg)

this is when i try to open it as ADMINISTRATOR

**Comment by iceMongus** [comment] 2022-01-03 17:34
![Screenshot 2022-01-03 193221](https://user-images.githubusercontent.com/11286566/147961324-ebae740a-c1f9-474f-b735-c5f31ac4c4be.jpg)

this is i GET when hit the START !!

**Comment by iceMongus** [comment] 2022-01-03 17:34
and this is my configuration 
![Screenshot 2022-01-03 193245](https://user-images.githubusercontent.com/11286566/147961374-b837d4d5-c361-4e16-8516-07fc7460ab86.jpg)

**Comment by Gkiokan** [comment] 2022-01-03 17:42
> it somehow runs !!.. sometimes runs and some do not. when run doing nothing !! when i try to upload the package and hit RESUME i got this msg ![Screenshot 2022-01-03 191413](https://user-images.githubusercontent.com/11286566/147959834-2c21a8df-cff8-4afc-867c-d4c8759784b7.jpg)

Could you open the PS4 API Info window, too and check for logs what the RPI on your PS4 responds with?
The extended Row allows for further Operation Buttons. Resume assumes that you have a task already running (press the play button to install or start) which sends the install request to your PS4.

I am currently adding some error catchers to the app itself and will add also add error handlers for that.
I'll be back after testing it on windows 10, gimme some hours to test it before releasing a patch.

Also I think maybe the running error - may - be a problem with the portable version, so I will release a unpacked edition, too.

**Comment by iceMongus** [comment] 2022-01-03 18:28
![Screenshot 2022-01-03 195742](https://user-images.githubusercontent.com/11286566/147966031-4de83563-f822-4abc-b8f9-7481baed4b38.jpg)

**Comment by iceMongus** [comment] 2022-01-03 18:28
![Screenshot 2022-01-03 202557](https://user-images.githubusercontent.com/11286566/147966051-1b9b9b45-060d-40f8-b1ba-4ac5fb918070.jpg)

**Comment by Gkiokan** [comment] 2022-01-03 18:30
@iceMongus Can you please try the unpacked Version?
[PS4 Remote Package Sender v2.4.0 win-unpacked](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/download/v2.4.0/PS4.Remote.PKG.Sender.V2-2.4.0-win.zip)

**Comment by iceMongus** [comment] 2022-01-03 18:34
1st try to run unpacked version was unsuccessful .. start in white poard 
but 2nd try was successfull

**Comment by iceMongus** [comment] 2022-01-03 18:35
when i try to start sending i got request timeout

**Comment by iceMongus** [comment] 2022-01-03 18:42
10 try's 3 was succesful and 7 not but strange is on fort try ask me to add exeption in firewall rules

**Comment by Gkiokan** [comment] 2022-01-03 18:43
> 10 try's 3 was succesful and 7 not but strange is on fort try ask me to add exeption in firewall rules

Sure because the Tool want to communicate with the PS4 in your network which is on another IP.
That may be one of the firewall issues that is causing the request timeout if the PS4 IP Address is correct.

**Comment by iceMongus** [comment] 2022-01-03 18:44
my network is in range 10.10.11.0/24
my PC is 10.10.11.10 and my PS4 is 10.10.11.30

**Comment by iceMongus** [comment] 2022-01-03 18:46
> That may be one of the firewall issues that is causing the request timeout if the PS4 IP Address is correct.

https://user-images.githubusercontent.com/11286566/147966031-4de83563-f822-4abc-b8f9-7481baed4b38.jpg

**Comment by iceMongus** [comment] 2022-01-03 19:12
I try to start 5 times to upload what I have in my queue and all the time I got Timeout on Request BUT on 5th time RPI on my console crashed with msg 

"An error has occurred in the following application.
 (CE-34878-0)
Remote PKG installer

**Comment by Gkiokan** [comment] 2022-01-03 19:16
Glad you could get it working. Once the install request is out, the progress bar should fill up and you should see the PS4 API Logs growing. 

The CE-34878-0 Error is a unspecific Error from the PS4 itself. Restart the RPI, delete the unfinished file and try again.

What do you mean by 5th time? It should start directly installing on first request and have an eye on the PS4 API Logs Window.

**Comment by iceMongus** [comment] 2022-01-03 19:19
the problem is UPLOAD NOT STARTING !!! there is nothing to delete on the console ...

**Comment by iceMongus** [comment] 2022-01-03 19:21
> What do you mean by 5th time?
every fifth time ... that's I mean

**Comment by Gkiokan** [comment] 2022-01-03 19:24
I see. It seems the unpacked version works just better then the portable regarding the starting errors.

I am just on it about to debug the install request what happens.

**Comment by Gkiokan** [comment] 2022-01-03 19:33
I think I have found the bug. The request never starts because there is an hidden exception on windows.
I am fixing it now.

**Comment by Gkiokan** [comment] 2022-01-03 19:45
I have found the Error. It was a missing port configuration in the default settings for the ps4.
Shame on me. This happens when you try to hurry up on configs.

I am just building the new patch. Gimme 10 Mins for building and uploading them and then try it.

**Comment by Gkiokan** [comment] 2022-01-03 20:08
![image](https://user-images.githubusercontent.com/7249224/147973543-649ce851-dae3-4541-acf4-d05f6e9302cb.png)
You can see here the working Version on Windows 10.

Checkout the new release v2.4.1 which fixes the request error and have an errorCatcher.
[Release v2.4.1](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.4.1)

**Comment by pgroot91** [comment] 2022-01-03 23:25
Looks pretty sexy now! Haven't had the time to actually use it but it seems it's working now 👍

**Comment by iceMongus** [comment] 2022-01-04 07:42
so far so good atm starts normal from 1st time and showing API Logs too 
start package transfer too !! good work mate !
But it's still buggy in some cases .. 
on About change version and please put help on mouse hover on button's

**Comment by iceMongus** [comment] 2022-01-04 08:21
on check i got this:
![Screenshot 2022-01-04 101930](https://user-images.githubusercontent.com/11286566/148029798-eee37686-6f13-43ce-bd4f-78289074eeea.jpg)

**Comment by iceMongus** [comment] 2022-01-04 08:23
and as i mention in my config tab 
![Screenshot 2022-01-04 102217](https://user-images.githubusercontent.com/11286566/148030031-cc80fa30-d892-4c8b-b9be-ab259c4c9c68.jpg)

**Comment by iceMongus** [comment] 2022-01-04 09:01
this one works for me on 70% have some issues but at all is working and normal installing packages remotely !! interface is ... but work 

https://github.com/sonik-br/PS4RPIGUI

**Comment by Gkiokan** [comment] 2022-01-04 11:28
@iceMongus Your Heartbeat is not working. Check the Server Window for Errors. Usually this is a blocked port. Just apply a new Port Number and restart the server (by pressing apply, the refresh button or the I/O) or directly in the Server Window.

The ErrorCatcher does what it should do to prevent the app crashing. I'll fix that line that is caused by a failing hearthbeat check. Jut a typo there.

I will add a Troubleshoot.md for all possible failing szenarious. Timeout, White Screen of Dead, PS not found... 

The latest version has been tested already by some ppl on windows 10 working fine sofar.

**Comment by Gkiokan** [comment] 2022-01-04 20:01
I've just released a new patch with deeper logging.  
Everything should work fine now as it is already tested successfully by some windows users, too.

If you have any new issue, feel free to open a new issue. I think we can close this for now.

**Closed by Gkiokan** 2022-01-04 20:01 UTC
Labels: win11
