### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by andersonmoura** [Gkiokan/ps4-remote-pkg-sender#58] opened 2023-02-25 14:54 UTC
I'm using the latest version but i keep receiving "error on install" with any package a try.

```
Latest Version Info
You are currently on Version 2.8.0 
Latest Release Version is 2.8.0 
```

Here is the PS4 API Logs:

```
1677336104911 | Matt Hoffman's Pro BMX 2_PS2.pkg error on install
1677336104910 | Matt Hoffman's Pro BMX 2_PS2.pkg install
1677336104899 | Install Request
1677336104899 | Matt Hoffman's Pro BMX 2_PS2.pkg prepare start installing
1677336102936 | Matt Hoffman's Pro BMX 2_PS2.pkg can be installed.
1677336098369 | PS4 is accessible
```

Another Package:

```
1677336838654 | Chernobylite.PS4-DUPLEX.pkg error on install
1677336838654 | Chernobylite.PS4-DUPLEX.pkg install
1677336838641 | Install Request
1677336838641 | Chernobylite.PS4-DUPLEX.pkg prepare start installing
1677336835181 | Chernobylite.PS4-DUPLEX.pkg can be installed.
```

**Comment by Gkiokan** [comment] 2023-02-26 13:16
Probably same error as [here](https://github.com/Gkiokan/ps4-remote-pkg-sender/issues/20). 

Could you check if the game already has been installed? Delete it and try again.  
Probably you are also on low storage, that error isn't reported well but can lead into install errors.

**Comment by andersonmoura** [comment] 2023-02-26 18:47
+500GB free on storage!
Removed all notifications.
Tried a new game... same result 

```
1677437125792 | 1.Asterix.and.Obelix.Slap.Them.All_CUSA23755_v1.00_[8.50]_OPOISSO893.pkg error on install
1677437125791 | 1.Asterix.and.Obelix.Slap.Them.All_CUSA23755_v1.00_[8.50]_OPOISSO893.pkg install
1677437125779 | Install Request
1677437125779 | 1.Asterix.and.Obelix.Slap.Them.All_CUSA23755_v1.00_[8.50]_OPOISSO893.pkg prepare start installing
1677437122375 | 1.Asterix.and.Obelix.Slap.Them.All_CUSA23755_v1.00_[8.50]_OPOISSO893.pkg can be installed.
1677437114506 | PS4 is accessible
```

**Comment by Gkiokan** [comment] 2023-02-26 18:55
This is strange. Do you get any error that pops up besides the logs?   
What happens exactly. Does it spin and nothing happens?  
What is your PS4 FW Version and which GoldHen do you use?  
Probably try a older GoldHen version, 2.1 or even 2.0.  

There was a similar issue back on the swap from 1.8 to 2.1 and it was due the GoldHen JB version.  
This was fixed one revision later.  Probably the same solution from the [see Troubleshooting Guide - timeout option c,d,e](https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#i-get-timeout-error)

**Comment by andersonmoura** [comment] 2023-02-26 19:26
I'm on FW 9.0.0. Was using GodHenV2.3 but just tried with 2.2.4 and with 2.1.2

I get no erros on screen. It shows me the notification on the ps4 that the payload was received and after that... nothing!!!


![2023-02-26_16h14_59](https://user-images.githubusercontent.com/1872176/221432019-f1b95509-9677-4727-b5dc-580adb6997cd.png)

![2023-02-26_16h15_08](https://user-images.githubusercontent.com/1872176/221432026-4157cd60-158f-4dae-b76f-9c52b2c0b9d3.png)

Already tried to disable windows firewall and run as admin, but not seems to work

I don't mean to waste your time with this... I'm able to use another tool to send the fpkgs. Just tried with PS4RPS and worked just fine...

I'm reporting cause i like this tool better and maybe others can run in the same issue!

**Comment by Gkiokan** [comment] 2023-02-26 19:33
Thanks man, it's okay, I care about my app, it's not wasting time if we can fix something that makes the app better for all.  
Oh yea, @njzydark did a good job on his RPS, too.  But this error gives me truly questions marks now.  
  
@njzydark Any clue mate what could cause this issue? Hard to reproduce the error if doesn't happen to me at all but even worse if we don't have any errors at all. I did never check if flatZ RPI does create logs at all.

**Comment by Gkiokan** [comment] 2023-02-26 19:49
@andersonmoura There comes one Idea in my mind. You could clone the repo locally, install the dependencies and try to run the application in dev mode. This allows you to see the internal application logs.  If you mind you can try it and see what the ps4 really responds with or maybe there is an error that throws and crashes the flow unexpected.  
 
Logs will be shown in the console and DevTools. 
To do so you  need to have at least node v14.17 installed.  
  
`git clone https://github.com/Gkiokan/ps4-remote-pkg-sender.git` 
`cd ps4-remote-pkg-sender`   
`npm i ` (installs the dependencies, only needed once). 
`npm run watch` starts the application in dev mode with DevTools.  

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/7249224/221433385-d4fa5e3c-29ce-444b-a6f2-71e7daefd10b.png">

**Comment by Masamune3210** [comment] 2023-03-09 22:51
Having things suddenly work fine when built with different parameters makes me wonder if there is a timing issue somewhere

**Comment by andersonmoura** [comment] 2023-03-10 13:12
> This is really really strange. Even more strange when we can't reproduce the error in dev mode. Looks like we must search a needle in the haystack.
> 
> There would be two more option to reproduce this. If you would build the application with dev mode enabled into the production or build it on your machine.
> 
> But first you could try to build the application yourself with `npm run build` which should give you a working production version and builds with the Operating System required dependencies ( just in case Windows 11 ? ) does require something special for your case.
> 
> The other solution would be to enable the dev tools in the command, build the production build and see what Error happens.
> 
> Not really sure if this helps, but you could also try to change the Server Port from the ps4 server - not that it makes any difference until it conflicts but give it a try.
> 
> If you need help with that, contact me on TG or Discord.

Yeah.. I'm on Windows 11 22H2. I'm not sure if I understood right... I'm need do add some extra dependencie before build the versio?

**Comment by Gkiokan** [comment] 2023-03-10 23:55
This is really rediclious. Good job on running the dev mode in production build. This makes a good starting point. By Looking at the logs you can see, that there is an `xyz error on install` log happening, but by the code it doesn't return anything after, so the data is null which should never happen. So the thing is, there is a generic error that the ps4 tries to tell us and we don't understand it.  

Sofar the theoretical part. For resolving that, could you try to replace the then callback method by the following and try again on a build prod?  
With this you should be able to see the whole response object from the ps4.  

```js
// replace the then callback
// /pages/Index.vue @ 266
              .then( res ) => {
                  let data = res.data
                  this.log(file.name + ' install', data)
                  console.log("Install full response", res)

                  if( data.status == 'success'){
                      this.$store.dispatch('queue/addTask', data)

                      this.setTask(file, data.task_id)
                      this.setStatus(file, 'installing')
                      this.sendNotification({ title: "Installing", body: file.name + " is installing" })
                      this.startInterval(file)

                      this.log(file.name + ' has been started installing with Task ID ' + data.task_id, data)
                  }
                  else {
                      console.log(file.name + " error on install", data)
                      this.log(file.name + " error on install", data)
                  }

              })
```

**Comment by andersonmoura** [comment] 2023-03-11 15:24
So, are we losting the 'data' somewhere in the way? 

![2023-03-11_12h20_33](https://user-images.githubusercontent.com/1872176/224492636-95aa1889-8ba5-4dfd-981b-2cbb1f0c3bc3.png)

**Comment by Gkiokan** [comment] 2023-03-12 01:45
As you can see the install request itself to the ps4 seems fully correct.  
But the response has a status 200 with no Response (which should be 204 to be precise).  
But even then, I've never seen this behavior.  Gonna check if there is something similar happening with flatZ RPI or the OOP RPI. So yea, we are missing the data from the response.  

You did try flatZ RPI and the OOP RPI right? Both with the same behavior in prod mode?  
Does the error happens on other PKG files, too?  
The same file does work in dev mode, too?
 
Just for the sake of beeing tested, try to set the Request Timeout to maximum at the Config view.  
Even it's not beeing reported as a timeout error it may be worth to try it.

**Comment by andersonmoura** [comment] 2023-04-01 11:35
Actually I'm using OOP RPI!

I've the Request Timeout set at 8000ms and the same fpkg with problem in prord mode, USED to work in dev mode as I showed previously. 

I mean 'used' because I just ran all again and now, dev mod shows the same behavior as prod mod. I get just a notification of the sent payload, a '200' status code response and no info in 'data'.

Dev mode now with the same behavior as prod mode
![2023-04-01_08h35_25](https://user-images.githubusercontent.com/1872176/229286396-6a103a46-c0c5-4296-87cd-6f5bc60b753d.png)

**Comment by Gkiokan** [comment] 2023-04-05 18:29
Very Strange. Is this the same game?  Is this the full game with updates?  
Try checking if there is something on the Notifications for this game.  

But it makes no sense that even the dev mode does run into this problem now.  
Could you check your processes and see if there is any other node or express service is running and kill everything and restart the app again? 

I thought about a config reset but that shouldn't affect anything. Alternatively try another port.   

If this still troubles you, you could try LM's ItemzFlow as it does now allow to install from shared drives. MW has a Tutorial on it. Just for the sake of getting your job done for now because I am still busy with my projects and it may take a bit longer until I get back to the sender.

**Comment by Masamune3210** [comment] 2023-04-05 18:38
Unfortunately, it uses NFS. Would be wonderful if it also supported SMB lol

**Comment by Gkiokan** [comment] 2023-04-06 14:59
You know I could add another feature of serving the PKG File from the PKG Sender as NFS / SMB but I have no time for it. However MW showed some workarounds on how to get it running in combination with SMB I think. If you combine SMB into the same folder that is shared as NFS it should actually work.

Ofc, this is still another programm and no interactive easy usage and blabla. We have to wait a bit until everything comes together.

**Comment by Masamune3210** [comment] 2023-04-06 15:46
The main problem is there just isn't a good open source and non-buggy NFS implementation for Windows. Honestly, it's much easier to just use ftp to push the odd game package every once in a while and let the package manager install it.

**Comment by Gkiokan** [comment] 2023-04-07 09:43
Yea as we have discussed this before this would be probably a more stable approach when we send the games though FTP to the PS4. The downside is still that the users will need 2x of the space before they can install the games.  

However next to this integrated FTP feature there would be also a integrated Cheat Manager included which could be cool for some users who are actively cheating. 

I hope I can schedule some updates between Mai - June 2023.

**Comment by Gkiokan** [comment] 2023-09-06 23:27
Just to clear stuff out I will close this issue for now. Doesn't seem to be happen to anyone else, so this must be something unique that I can debug with you together on a Video Call. If you need anything find me on Discord or Telegram by my Name.

At least it seems to be not a big problem anymore? Still strange. HF with the new version anyway.

**Closed by Gkiokan** 2023-09-06 23:27 UTC
